[project]
name = 'decentralized-reputation-system'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.decentralized-reputation-system]
path = 'contracts/decentralized-reputation-system.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
